# Generated by Django 3.0.3 on 2020-08-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='update_type',
            field=models.CharField(choices=[('1', 'Weekly'), ('2', 'Daily'), ('3', 'Monthly')], default='1', max_length=1),
        ),
    ]
