# Generated by Django 3.0.3 on 2020-08-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200809_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='task_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
    ]
